### PR TITLE
[JEP-222] - Update to Remoting 4.0. Add support for WebSockets.

### PR DESCRIPTION
**Pull request by jeffret-b**
This Remoting release adds support for WebSockets. See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.0) for full details.

### CODE REVIEW

**Comment by jglick** [comment]
see also https://github.com/jenkinsci/docker-jnlp-slave/pull/145

**Comment by jeffret-b** [comment]
Try a rebuild?

**Comment by jeffret-b** [comment]
Are there still infra problems?

**Comment by jeffret-b** [comment]
There seems to be a CI infrastructure issue with an unavailable Windows agent. Do we need to file an infra ticket? What would that be? Or adjust the Jenkinsfile? Any ideas? @slide

**Comment by slide** [comment]
Yes, that would be good. I am trying to find the logs for the agent, but am not having much luck.

**Comment by slide** [comment]
File a ticket would be good...

**Comment by jeffret-b** [comment]
Any ideas what to say in the ticket? Something about no `windock` agent?

**Comment by slide** [comment]
You can specify that the Azure VM Agent for win2019 is not spinning up correctly.

**Comment by jeffret-b** [comment]
Thanks!

Infra PR filed: https://issues.jenkins-ci.org/browse/INFRA-2451

**Pull request merged**
