### PR TITLE
[JENKINS-51986] - Add Java 11 support to documentation

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Documents #34 

https://issues.jenkins-ci.org/browse/JENKINS-51986

### CODE REVIEW

**Comment by carlossg** [comment]
`latest-jdk11` is setup but the other ones not yet

**Comment by oleg-nenashev** [comment]
I will do that. I have access to DockerHub so I can configure the build accordingly

**Comment by alecharp** [comment]
I'd be in favor to remove the `alpine` reference from this until we have a clear plan and availability of `alpine` based images.

**Comment by carlossg** [comment]
there is alpine jdk-12 ea

**Comment by alecharp** [comment]
LGTM :bee:

**Comment by oleg-nenashev** [comment]
> LGTM, but I would really like to rename this repo and all downstream things as needed.

If you have time to work on it, you are more than welcome to do that. Personally I want to completely rework the Docker agent release flow: https://issues.jenkins-ci.org/browse/JENKINS-54460 . It's IMHO more important for the project, and it would also resolve the image naming issue.

**Comment by oleg-nenashev** [comment]
The main issue with https://issues.jenkins-ci.org/browse/INFRA-1105 is that we would need to rename images in documentation everywhere. So it is a bigger chunk of work than just creating a new DockerHub Repo. I would prefer to reserve jenkins/agent and jenkins/jnlp-agent for a proper release flow running on Trusted CI

**Pull request merged**
