### PR TITLE
Initial commit of Windows docker image support.

### PR DESCRIPTION
**Pull request by slide**
- Currently only supports Windows Server Core
- Files in place to support nanoserver, but more testing needs to be done
- Both JDK 8 and JDK 11 images are supported

Feedback welcome!

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Plugin management is not available ATM, right?

**Comment by slide** [comment]
This is the agent docker image, not the master.

**Comment by oleg-nenashev** [comment]
oops

**Comment by slide** [comment]
Once this is merged, how do you want to get an initial image published as we don't have agents on ci.jenkins.io (or trusted right now either) that support building docker images on Windows?

**Comment by oleg-nenashev** [comment]
Manual push is fine with me (can grant you permissions), ideally would
prefer a DockerHub autobuild

**Comment by slide** [comment]
DockerHub does not support Windows builds. They have had it on their roadmap since 2017, but seems no progress.

**Comment by slide** [comment]
FYI, my end goal with this is to have docker agents available to ci.jenkins.io and trusted.ci. Once that is in place, these can be auto-built and published like the current Linux agent images are.

**Pull request merged**
