### PR TITLE
Switch all Dockerfiles to remoting 3.35

### PR DESCRIPTION
**Pull request by alxsap**
@oleg-nenashev In https://github.com/jenkinsci/docker-slave/pull/74 I missed to adjust the other Dockerfiles as well 😕
Sorry for that.

### CODE REVIEW

**Comment by alxsap** [comment]
@oleg-nenashev @jeffret-b any thoughts on this? We (I) missed to update the other Dockerfiles with the new remoting version.

**Comment by oleg-nenashev** [comment]
These missed versions and a serious of regressions last week shows that I
need a break before I can review PRs properly. Please proceed without me
for now, I am on vacation and need some time to recover

**Comment by alxsap** [comment]
@oleg-nenashev thanks. Enjoy your vacation 😊

**Comment by alxsap** [comment]
PS: who can release a new docker-slave version?

**Comment by slide** [comment]
Once it's merged it should be auto built on dockerhub

**Comment by alxsap** [comment]
> Once it's merged it should be auto built on dockerhub

Ah, ok. Good to know.
But what I meant is a stable version like `3.35-3-alpine` to reference in [docker-jnlp-slave](https://github.com/jenkinsci/docker-jnlp-slave)

**Comment by slide** [comment]
I'm not sure how those tags get created.

**Comment by alxsap** [comment]
> I'm not sure how those tags get created.

@slide It seems Oleg [switched](https://github.com/jenkinsci/docker-slave/commits/master/.github/release-drafter.yml) to [release-drafter](https://github.com/apps/release-drafter) 9 days ago. Before he created the tags manually.

I guess owners of the repo should see a new draft release?

> As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready

**Pull request merged**
