### PR TITLE
Update Windows containers

### PR DESCRIPTION
**Pull request by slide**
- Use AdoptOpenJDK instead of plain OpenJDK
- Fix issues with passwords expiring
- Fix user creation issue
- Add Git and Git LFS
- Update versions
- Add tests

### CODE REVIEW

**Comment by slide** [comment]
It passes all the tests that the Linux container has. I am still working on bringing up a full local testing environment to test it. Do you have details on how you test things in your test environment?

**Comment by MarkEWaite** [comment]
> Do you have details on how you test things in your test environment?

I'm not sure that my local environment will be any help.  The public portion of my local environment is described in my [lts-with-plugins branch](https://github.com/MarkEWaite/docker-lfs/tree/lts-with-plugins).  That includes `docker_build.py` to create the local images and `docker_run.py` to run the images.

The private portion of the local environment includes credentials and agents and jobs which require credentials and agents.  Some of those agents have docker, but none of them are able to run Windows docker images (I'm not that modern yet).

**Comment by slide** [comment]
Updated to WIP to do some more testing locally

**Comment by slide** [comment]
I did some more extensive testing with some maven builds and so forth and things look good, so I am happy with this.

**Comment by MarkEWaite** [comment]
That's great.  Thanks so much!  Approved to merge!

**Pull request merged**
