### PR TITLE
Provide image which is based on Debian 10/buster

### PR DESCRIPTION
**Pull request by krichter722**
Debian 9 although stable is quite old in terms of up-to-date versions of software.

### CODE REVIEW

**Comment by krichter722** [comment]
@rtyler Thanks for merging this. Can you estimate when the image tag `latest-jdk11-buster` will be available?

**Comment by slide** [comment]
I think the dockerhub builds need to be updated to.build that dockerfile

**Comment by krichter722** [comment]
@slide Can this be done in a PR that I could create or is it an administrative task that needs to be done by someone with access rights.

**Comment by slide** [comment]
It needs to be done by someone with write access on the repo on dockerhub. I am not sure who that is.

**Comment by slide** [comment]
You can see the existing builds here: https://hub.docker.com/r/jenkins/slave/builds

One would need to be added to create a build using the dockerfile added.

**Pull request merged**
