### PR TITLE
add Group flag

### PR DESCRIPTION
**Pull request by joppa27**
just added the missing `-G` to the adduser command.
Good catch by  @jwieringa

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@carlossg @dduportal any concerns regarding the downstream images?

**Comment by dduportal** [comment]
@oleg-nenashev @joppa27 Good catch ! 

Improvement proposal: following the method used on the officiel jenkins image (https://github.com/jenkinsci/docker/blob/master/Dockerfile#L17 ) , by combining `ARG` and `ENV` instruction to providable customizable agent and group, thus avoiding this kind of confusion in the future.

It also let the end user to use the mapping they want ( the label is just a facility: uid and gid are much needed since the jenkins docker usages tend to bind mount volume to the host).

**Comment by dduportal** [comment]
@oleg-nenashev but you can merge this here, got my 🐝  (and my axe :p )

**Comment by oleg-nenashev** [comment]
Let's see how the automatic build flies

**Comment by dduportal** [comment]
Thanks for the contribution @joppa27 and @jwieringa ! This is much welcome !

**Pull request merged**
